version: '3.8'

services:
  django-app:
        
    image: raniaiset/managepython:${IMAGE_TAG}
    container_name: django-app
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"     
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./data/db.sqlite3:/app/db.sqlite3 
      - .:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=changeme
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]