version: '3.8'

services:
  django-app:
        
    image: app-django:latest  # Utilisation de l'image app-django:latest
    container_name: django-app
    ports:
      - "8011:8000"
    volumes:
      - ./static:/app/static
      - ./media:/app/media
      - ./data/db.sqlite3:/app/db.sqlite3  # Assurez-vous que le chemin correspond à celui du Dockerfile
    environment:
      - DEBUG=True
    networks:
      - app-network

networks:
  app-network:
    driver: bridge