version: '3.8'

services:
  django-app:
        
    image: raniaiset/managepython:${IMAGE_TAG}
    container_name: django-app
    network_mode: bridge
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"     
    volumes:
      - .:/app
    
  
